---
run:
  timeout: 5m
  go: "1.20"
  skip-files:
    - "zz_generated.*\\.go$"
  allow-parallel-runners: true

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  goheader:
    values:
      regexp:
        license-year: (202[0-9]|20[3-9][0-9])
    template: |-
      Copyright {{license-year}} The Kubernetes Authors.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
  nlreturn:
    block-size: 2
  stylecheck:
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016"]
    dot-import-whitelist:
      - "github.com/onsi/gomega"
  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: k8s.io/apimachinery/pkg/util/runtime
        alias: utilruntime
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      # CAPI
      - pkg: sigs.k8s.io/cluster-api/api/v1beta1
        alias: clusterv1
      - pkg: sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3
        alias: clusterctlv1
      - pkg: sigs.k8s.io/cluster-api/cmd/clusterctl/client/config
        alias: configclient
      # CAPI Add-on Provider Helm
      - pkg: sigs.k8s.io/cluster-api-addon-provider-helm
        alias: addonsv1alpha1
issues:
  exclude:
    # Not all platforms are supported by this provider, those which aren't
    # supported will be caught by the default case in the switches.
    - "missing cases in switch of type v1.PlatformType: (\\.*)"
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
    - path: hack/boilerplate
      linters:
        - goheader
